    dn E3, 1, $F03
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn E3, 1, $C20
    dn E4, 1, 0
    dn E4, 1, $C20
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn A3, 1, 0
    dn A3, 1, $C20
    dn 90, 1, 0
    dn 90, 1, 0
    dn A#3,1, 0
    dn B3, 1, $30A
    dn 90, 1, $30A
    dn 90, 1, 0
    dn 90, 1, 0
    dn B3, 1, $C20
    dn D4, 1, 0
    dn D4, 1, $C20
    dn 90, 1, 0
    dn 90, 1, 0
    dn D4, 1, 0
    dn D4, 1, $C20
    dn F#3,1, $C80
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn G3, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn F#3,1, $C20
    dn G4, 1, 0
    dn G4, 1, $C20
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn A3, 1, 0
    dn A3, 1, $C20
    dn A#3,1, $C80
    dn A#3,1, $C20
    dn A#3,1, $101
    dn B3, 1, $30A
    dn 90, 1, $30A
    dn 90, 1, 0
    dn D4, 1, 0
    dn D4, 1, $C20
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn A3, 1, 0
    dn A3, 1, $C20
    dn B3, 1, 0
    dn 90, 1, 0
    dn 90, 1, 0
    dn 90, 1, $D01
